name: Mining Stock Analysis CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  # Updated from v2
    - name: Set up Python
      uses: actions/setup-python@v5  # Updated from v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m venv mining-env
        source mining-env/bin/activate
        pip install -r requirements.txt
    - name: Run tests
      run: |
        source mining-env/bin/activate
        python -m unittest discover tests
    - name: Generate report
      run: |
        source mining-env/bin/activate
        python src/main.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4  # Updated from v2
      with:
        name: report
        path: report.md
        retention-days: 90  # Specify how long to retain the artifact